# -*- coding: utf-8 -*-
"""
BlokQR - Module 1 (n4) : palier RAPIDE par defaut + flag deep pour le sandbox.

Corrige le bug "failed" intermittent : le sandbox Chromium ne tourne plus dans
le chemin synchrone par defaut. /v1/analyze renvoie un verdict rapide et fiable
(lexical + redirections + domaine + threat intel) -> plus de verdict UNKNOWN du
au depassement de budget. Le rendu Chromium passe derriere un flag deep=True,
reutilise par le futur /v1/analyze/deep (Pro). La cle de cache distingue les
paliers fast/deep.

Modifie :
  * app/pipeline.py        (signature analyze + flag deep + cle de cache)
  * app/analysis_cache.py  (cache_key inclut le palier)

A executer DEPUIS /opt/blokqr/backend :
    cd /opt/blokqr/backend
    python3 patch_m1_fast_tier.py

Idempotent. Contenus base64. Abandon si une ancre est absente. Controle de syntaxe.
"""
import ast, base64, io, sys
dec=lambda s: base64.b64decode(s).decode("utf-8")

PIPE=[['YXN5bmMgZGVmIGFuYWx5emUoCiAgICByZXF1ZXN0OiBBbmFseXplUmVxdWVzdCwgc2V0dGluZ3M6IFNldHRpbmdzLCBzaWduZXI6IFZlcmRpY3RTaWduZXIKKSAtPiBTaWduZWRWZXJkaWN0OgogICAgIiIiRXjDqWN1dGUgbGUgcGlwZWxpbmUgY29tcGxldCBldCByZW52b2llIHVuIHZlcmRpY3Qgc2lnbsOpLiIiIg==', 'YXN5bmMgZGVmIGFuYWx5emUoCiAgICByZXF1ZXN0OiBBbmFseXplUmVxdWVzdCwgc2V0dGluZ3M6IFNldHRpbmdzLCBzaWduZXI6IFZlcmRpY3RTaWduZXIsCiAgICAqLCBkZWVwOiBib29sID0gRmFsc2UsCikgLT4gU2lnbmVkVmVyZGljdDoKICAgICIiIkV4w6ljdXRlIGxlIHBpcGVsaW5lIGQnYW5hbHlzZSBldCByZW52b2llIHVuIHZlcmRpY3Qgc2lnbsOpLgoKICAgIGRlZXA9RmFsc2UgKGdyYXR1aXQpIDogcGFsaWVyIFJBUElERSwgc2FucyByZW5kdSBDaHJvbWl1bSBzeW5jaHJvbmUKICAgIChsZXhpY2FsICsgcmVkaXJlY3Rpb25zICsgZG9tYWluZSArIHRocmVhdCBpbnRlbCkgLT4gcsOpcG9uc2UgcmFwaWRlIGV0CiAgICBmaWFibGUsIGphbWFpcyBkZSB2ZXJkaWN0IFVOS05PV04gZMO7IMOgIHVuIGTDqXBhc3NlbWVudCBkZSBidWRnZXQgZHUgc2FuZGJveC4KICAgIGRlZXA9VHJ1ZSAoUHJvLCB2aWEgL3YxL2FuYWx5emUvZGVlcCkgOiBham91dGUgbGUgcmVuZHUgZHluYW1pcXVlIENocm9taXVtLgogICAgIiIi', '*, deep: bool = False,'], ['ICAgIGNhY2hlID0gZ2V0X2NhY2hlKHNldHRpbmdzKQogICAgY2tleSA9IGNhY2hlX2tleShyZXF1ZXN0KQ==', 'ICAgIGNhY2hlID0gZ2V0X2NhY2hlKHNldHRpbmdzKQogICAgY2tleSA9IGNhY2hlX2tleShyZXF1ZXN0LCBkZWVwKQ==', 'cache_key(request, deep)'], ['ICAgICAgICBpZiBub3QgcHJpdmFjeV9ob2xkOgogICAgICAgICAgICBpbnRlbF90YXJnZXQgPSByZXBvcnQuZmluYWxfdGFyZ2V0IG9yIGNsYXNzaWZpZWQudXJsCgogICAgICAgICAgICBhc3luYyBkZWYgX3J1bl9keW5hbWljKCk6CiAgICAgICAgICAgICAgICBpZiBub3QgZmluYWxfdXJsOgogICAgICAgICAgICAgICAgICAgIHJldHVybiBOb25lCiAgICAgICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAgICAgcmV0dXJuIGF3YWl0IGFzeW5jaW8ud2FpdF9mb3IoCiAgICAgICAgICAgICAgICAgICAgICAgIGFuYWx5emVfZHluYW1pYygKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGZpbmFsX3VybCwgc2V0dGluZ3MsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICB3YW50X3NjcmVlbnNob3Q9cmVxdWVzdC53YW50X3NjcmVlbnNob3QsCiAgICAgICAgICAgICAgICAgICAgICAgICksCiAgICAgICAgICAgICAgICAgICAgICAgIHRpbWVvdXQ9c2V0dGluZ3MuZHluYW1pY19idWRnZXRfc2Vjb25kcywKICAgICAgICAgICAgICAgICAgICApCiAgICAgICAgICAgICAgICBleGNlcHQgYXN5bmNpby5UaW1lb3V0RXJyb3I6CiAgICAgICAgICAgICAgICAgICAgcmV0dXJuIE5vbmUKCiAgICAgICAgICAgIGR5biwgaW50ZWwgPSBhd2FpdCBhc3luY2lvLmdhdGhlcigKICAgICAgICAgICAgICAgIF9ydW5fZHluYW1pYygpLAogICAgICAgICAgICAgICAgZ2F0aGVyX3RocmVhdF9pbnRlbChpbnRlbF90YXJnZXQsIHNldHRpbmdzKSwKICAgICAgICAgICAgKQogICAgICAgICAgICByZXBvcnQudGhyZWF0X2ludGVsID0gaW50ZWwKCiAgICAgICAgICAgIGlmIGR5biBpcyBub3QgTm9uZSBhbmQgZHluLmF2YWlsYWJsZToKICAgICAgICAgICAgICAgIHJlcG9ydC5jbG9ha2luZ19kZXRlY3RlZCA9IGR5bi5jbG9ha2luZ19kZXRlY3RlZAogICAgICAgICAgICAgICAgcmVwb3J0LmdhdGluZ19kZXRlY3RlZCA9IGR5bi5nYXRpbmdfZGV0ZWN0ZWQKICAgICAgICAgICAgICAgIGlmIGR5bi5pbXBlcnNvbmF0ZWRfYnJhbmQ6CiAgICAgICAgICAgICAgICAgICAgcmVwb3J0LmxvZ2luX3BhZ2VfaW1wZXJzb25hdGlvbiA9IGR5bi5pbXBlcnNvbmF0ZWRfYnJhbmQKICAgICAgICAgICAgICAgIHJlcG9ydC5zY3JlZW5zaG90X2I2NCA9IGR5bi5zY3JlZW5zaG90X2I2NAogICAgICAgICAgICAgICAgc2lnbmFscy5leHRlbmQoZHluLnNpZ25hbHMpCiAgICAgICAgICAgICAgICBpZiBkeW4uZmluYWxfdXJsIGFuZCBkeW4uZmluYWxfdXJsICE9IGZpbmFsX3VybDoKICAgICAgICAgICAgICAgICAgICByZXBvcnQuZmluYWxfdGFyZ2V0ID0gZHluLmZpbmFsX3VybAogICAgICAgICAgICAgICAgICAgIHJlcG9ydC5kaXNwbGF5ZWRfdmFsdWUgPSBkeW4uZmluYWxfdXJsCiAgICAgICAgICAgIGVsaWYgZmluYWxfdXJsOgogICAgICAgICAgICAgICAgIyBSZW5kdSBub24gYWJvdXRpIGRhbnMgbGUgYnVkZ2V0IGltcGFydGkgLT4gZmFpbC1jbG9zZWQuCiAgICAgICAgICAgICAgICBzaWduYWxzLmFwcGVuZChTaWduYWwoCiAgICAgICAgICAgICAgICAgICAgY29kZT0iZHluYW1pY19lcnJvciIsIHRpdGxlPSJBbmFseXNlIGR5bmFtaXF1ZSBpbmNvbXBsw6h0ZSIsCiAgICAgICAgICAgICAgICAgICAgZGV0YWlsPSJMZSByZW5kdSBkeW5hbWlxdWUgYSBkw6lwYXNzw6kgbGUgYnVkZ2V0IGRlIHRlbXBzIGltcGFydGkuIiwKICAgICAgICAgICAgICAgICAgICBzZXZlcml0eT1TZXZlcml0eS5JTkZPLCB3ZWlnaHQ9MCwgc291cmNlPSJkeW5hbWljIikp', 'ICAgICAgICBpZiBub3QgcHJpdmFjeV9ob2xkOgogICAgICAgICAgICBpbnRlbF90YXJnZXQgPSByZXBvcnQuZmluYWxfdGFyZ2V0IG9yIGNsYXNzaWZpZWQudXJsCgogICAgICAgICAgICBpZiBkZWVwOgogICAgICAgICAgICAgICAgIyBQYWxpZXIgUFJPRk9ORCAoUHJvKSA6IHJlbmR1IGR5bmFtaXF1ZSBDaHJvbWl1bSArIHRocmVhdCBpbnRlbAogICAgICAgICAgICAgICAgIyBFTiBQQVJBTEzDiExFLCBsJ8OpdGFwZSBkeW5hbWlxdWUgQk9STsOJRSBwYXIgdW4gYnVkZ2V0IGRlIHRlbXBzLgogICAgICAgICAgICAgICAgYXN5bmMgZGVmIF9ydW5fZHluYW1pYygpOgogICAgICAgICAgICAgICAgICAgIGlmIG5vdCBmaW5hbF91cmw6CiAgICAgICAgICAgICAgICAgICAgICAgIHJldHVybiBOb25lCiAgICAgICAgICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgICAgICAgICByZXR1cm4gYXdhaXQgYXN5bmNpby53YWl0X2ZvcigKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGFuYWx5emVfZHluYW1pYygKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBmaW5hbF91cmwsIHNldHRpbmdzLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHdhbnRfc2NyZWVuc2hvdD1yZXF1ZXN0LndhbnRfc2NyZWVuc2hvdCwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICksCiAgICAgICAgICAgICAgICAgICAgICAgICAgICB0aW1lb3V0PXNldHRpbmdzLmR5bmFtaWNfYnVkZ2V0X3NlY29uZHMsCiAgICAgICAgICAgICAgICAgICAgICAgICkKICAgICAgICAgICAgICAgICAgICBleGNlcHQgYXN5bmNpby5UaW1lb3V0RXJyb3I6CiAgICAgICAgICAgICAgICAgICAgICAgIHJldHVybiBOb25lCgogICAgICAgICAgICAgICAgZHluLCBpbnRlbCA9IGF3YWl0IGFzeW5jaW8uZ2F0aGVyKAogICAgICAgICAgICAgICAgICAgIF9ydW5fZHluYW1pYygpLAogICAgICAgICAgICAgICAgICAgIGdhdGhlcl90aHJlYXRfaW50ZWwoaW50ZWxfdGFyZ2V0LCBzZXR0aW5ncyksCiAgICAgICAgICAgICAgICApCiAgICAgICAgICAgICAgICByZXBvcnQudGhyZWF0X2ludGVsID0gaW50ZWwKCiAgICAgICAgICAgICAgICBpZiBkeW4gaXMgbm90IE5vbmUgYW5kIGR5bi5hdmFpbGFibGU6CiAgICAgICAgICAgICAgICAgICAgcmVwb3J0LmNsb2FraW5nX2RldGVjdGVkID0gZHluLmNsb2FraW5nX2RldGVjdGVkCiAgICAgICAgICAgICAgICAgICAgcmVwb3J0LmdhdGluZ19kZXRlY3RlZCA9IGR5bi5nYXRpbmdfZGV0ZWN0ZWQKICAgICAgICAgICAgICAgICAgICBpZiBkeW4uaW1wZXJzb25hdGVkX2JyYW5kOgogICAgICAgICAgICAgICAgICAgICAgICByZXBvcnQubG9naW5fcGFnZV9pbXBlcnNvbmF0aW9uID0gZHluLmltcGVyc29uYXRlZF9icmFuZAogICAgICAgICAgICAgICAgICAgIHJlcG9ydC5zY3JlZW5zaG90X2I2NCA9IGR5bi5zY3JlZW5zaG90X2I2NAogICAgICAgICAgICAgICAgICAgIHNpZ25hbHMuZXh0ZW5kKGR5bi5zaWduYWxzKQogICAgICAgICAgICAgICAgICAgIGlmIGR5bi5maW5hbF91cmwgYW5kIGR5bi5maW5hbF91cmwgIT0gZmluYWxfdXJsOgogICAgICAgICAgICAgICAgICAgICAgICByZXBvcnQuZmluYWxfdGFyZ2V0ID0gZHluLmZpbmFsX3VybAogICAgICAgICAgICAgICAgICAgICAgICByZXBvcnQuZGlzcGxheWVkX3ZhbHVlID0gZHluLmZpbmFsX3VybAogICAgICAgICAgICAgICAgZWxpZiBmaW5hbF91cmw6CiAgICAgICAgICAgICAgICAgICAgIyBSZW5kdSBub24gYWJvdXRpIGRhbnMgbGUgYnVkZ2V0IGltcGFydGkgLT4gZmFpbC1jbG9zZWQuCiAgICAgICAgICAgICAgICAgICAgc2lnbmFscy5hcHBlbmQoU2lnbmFsKAogICAgICAgICAgICAgICAgICAgICAgICBjb2RlPSJkeW5hbWljX2Vycm9yIiwgdGl0bGU9IkFuYWx5c2UgZHluYW1pcXVlIGluY29tcGzDqHRlIiwKICAgICAgICAgICAgICAgICAgICAgICAgZGV0YWlsPSJMZSByZW5kdSBkeW5hbWlxdWUgYSBkw6lwYXNzw6kgbGUgYnVkZ2V0IGRlIHRlbXBzIGltcGFydGkuIiwKICAgICAgICAgICAgICAgICAgICAgICAgc2V2ZXJpdHk9U2V2ZXJpdHkuSU5GTywgd2VpZ2h0PTAsIHNvdXJjZT0iZHluYW1pYyIpKQogICAgICAgICAgICBlbHNlOgogICAgICAgICAgICAgICAgIyBQYWxpZXIgUkFQSURFIChncmF0dWl0KSA6IHBhcyBkZSByZW5kdSBDaHJvbWl1bSBzeW5jaHJvbmUuCiAgICAgICAgICAgICAgICAjIENvcnJpZ2UgbGEgdmFyaWFuY2UgZGUgbGF0ZW5jZSAocGx1cyBkZSB2ZXJkaWN0IFVOS05PV04gZMO7IGF1CiAgICAgICAgICAgICAgICAjIGTDqXBhc3NlbWVudCBkZSBidWRnZXQgZHUgc2FuZGJveCkuIExhIHRocmVhdCBpbnRlbCByZXN0ZSBmYWl0ZS4KICAgICAgICAgICAgICAgIHJlcG9ydC50aHJlYXRfaW50ZWwgPSBhd2FpdCBnYXRoZXJfdGhyZWF0X2ludGVsKGludGVsX3RhcmdldCwgc2V0dGluZ3Mp', '# Palier RAPIDE (gratuit) : pas de rendu Chromium synchrone.']]
CACHE=[['ZGVmIGNhY2hlX2tleShyZXF1ZXN0OiBBbmFseXplUmVxdWVzdCkgLT4gc3RyOgogICAgIiIiQ2zDqSBkZSBjYWNoZSBMT1NTTEVTUyA6IHN5bWJvbG9naWUgKyBjaGFyZ2UgYnJ1dGUgZXhhY3RlLgoKICAgIE9uIGdhcmRlIGxhIGNoYXJnZSBicnV0ZSAoZXQgbm9uIHVuZSBmb3JtZSBub3JtYWxpc8OpZSkgcG91ciBuZSBqYW1haXMKICAgIGZ1c2lvbm5lciBkZXV4IGVudHLDqWVzIHF1aSBwb3VycmFpZW50IGRpZmbDqXJlciBzdXIgdW4gZMOpdGFpbCBpbmZsdWVuw6dhbnQgbGUKICAgIHZlcmRpY3QgKHBhcmFtw6h0cmUgZGUgcmVxdcOqdGUsIGZyYWdtZW50LCBjYXNzZSBkdSBjaGVtaW4uLi4pLiBMZSBub25jZSBjbGllbnQKICAgIG4nZW50cmUgcGFzIGRhbnMgbGEgY2zDqSA6IHVuIG3Dqm1lIFFSIHJlc2Nhbm7DqSBwYXIgbidpbXBvcnRlIHF1aSBmYWl0IG1vdWNoZS4KICAgICIiIgogICAgc3ltID0gKHJlcXVlc3Quc3ltYm9sb2d5IG9yICIiKS5sb3dlcigpCiAgICByZXR1cm4gZiJ7c3ltfXtfU0VQfXtyZXF1ZXN0LnJhd19wYXlsb2FkfSI=', 'ZGVmIGNhY2hlX2tleShyZXF1ZXN0OiBBbmFseXplUmVxdWVzdCwgZGVlcDogYm9vbCA9IEZhbHNlKSAtPiBzdHI6CiAgICAiIiJDbMOpIGRlIGNhY2hlIExPU1NMRVNTIDogcGFsaWVyICsgc3ltYm9sb2dpZSArIGNoYXJnZSBicnV0ZSBleGFjdGUuCgogICAgT24gZ2FyZGUgbGEgY2hhcmdlIGJydXRlIChldCBub24gdW5lIGZvcm1lIG5vcm1hbGlzw6llKSBwb3VyIG5lIGphbWFpcwogICAgZnVzaW9ubmVyIGRldXggZW50csOpZXMgcXVpIHBvdXJyYWllbnQgZGlmZsOpcmVyIHN1ciB1biBkw6l0YWlsIGluZmx1ZW7Dp2FudCBsZQogICAgdmVyZGljdCAocGFyYW3DqHRyZSBkZSByZXF1w6p0ZSwgZnJhZ21lbnQsIGNhc3NlIGR1IGNoZW1pbi4uLikuIExlIHBhbGllcgogICAgKGZhc3QvZGVlcCkgZW50cmUgZGFucyBsYSBjbMOpIHBvdXIgbmUgamFtYWlzIHJlc3NlcnZpciB1biB2ZXJkaWN0IHJhcGlkZSDDoAogICAgdW5lIGFuYWx5c2UgcHJvZm9uZGUgKG91IGwnaW52ZXJzZSkuIExlIG5vbmNlIGNsaWVudCBuJ2VudHJlIHBhcyBkYW5zIGxhCiAgICBjbMOpIDogdW4gbcOqbWUgUVIgcmVzY2FubsOpIHBhciBuJ2ltcG9ydGUgcXVpIGZhaXQgbW91Y2hlLgogICAgIiIiCiAgICBzeW0gPSAocmVxdWVzdC5zeW1ib2xvZ3kgb3IgIiIpLmxvd2VyKCkKICAgIHRpZXIgPSAiZGVlcCIgaWYgZGVlcCBlbHNlICJmYXN0IgogICAgcmV0dXJuIGYie3RpZXJ9e19TRVB9e3N5bX17X1NFUH17cmVxdWVzdC5yYXdfcGF5bG9hZH0i', 'deep: bool = False) -> str']]

def apply_edits(path, edits):
    try:
        src=io.open(path,"r",encoding="utf-8").read()
    except FileNotFoundError:
        print("  [IGNORE] %s introuvable"%path); return True
    changed=False
    for old_b,new_b,marker in edits:
        if marker in src: continue
        old=dec(old_b)
        if old not in src:
            print("  [ABORT] %s : ancre absente (%s) -> NON ecrit"%(path,marker)); return False
        src=src.replace(old,dec(new_b),1); changed=True
    if not changed:
        print("  [OK   ] %s : deja applique (idempotent)"%path); return True
    try: ast.parse(src)
    except SyntaxError as e:
        print("  [ABORT] %s : syntaxe invalide -> NON ecrit (%s)"%(path,e)); return False
    io.open(path,"w",encoding="utf-8").write(src)
    print("  [PATCH] %s : modifie"%path); return True

def main():
    ok=True
    ok&=apply_edits("app/pipeline.py", PIPE)
    ok&=apply_edits("app/analysis_cache.py", CACHE)
    if not ok: sys.exit(1)
    print("\n>>> Termine. Reconstruisez l'image puis redemarrez le conteneur.")

if __name__=="__main__":
    main()
