# -*- coding: utf-8 -*-
"""
BlokQR - Module 2a (n4) : entitlement Pro signe + route /v1/analyze/deep.

- CREE app/security/entitlement.py : jeton Pro signe (Ed25519 + ML-DSA),
  emis par /v1/billing/verify (Module 3), verifie cote serveur ET cote client
  (cles du manifeste). Modele bearer, sans identite (privacy-first).
- AJOUTE le champ `entitlement` a AnalyzeRequest (app/schemas.py).
- AJOUTE la route POST /v1/analyze/deep (Pro, deep=True -> sandbox Chromium),
  402 si l'entitlement est absent/invalide (app/api/routes.py).

A executer DEPUIS /opt/blokqr/backend :
    cd /opt/blokqr/backend
    python3 patch_m2a_deep_route.py

Idempotent. Contenus base64. Abandon si une ancre est absente. Controle syntaxe.
"""
import ast, base64, io, os, sys
dec=lambda s: base64.b64decode(s).decode("utf-8")

ENT_B64='IiIiSmV0b24gZCdlbnRpdGxlbWVudCBQcm8gc2lnbsOpIChFZDI1NTE5ICsgTUwtRFNBKS4KCkxlIGJhY2tlbmQgw6ltZXQgY2UgamV0b24gYXByw6hzIHbDqXJpZmljYXRpb24gZCd1biBhY2hhdCAodm9pciAvdjEvYmlsbGluZy92ZXJpZnkKYXUgTW9kdWxlIDMpLCBsZSBjbGllbnQgbGUgbWV0IGVuIGNhY2hlIGV0IGxlIHByw6lzZW50ZSBzdXIgL3YxL2FuYWx5emUvZGVlcC4KSWwgZXN0IHbDqXJpZmnDqSBjw7R0w6kgc2VydmV1ciAobcOqbWUgY2zDqSkgZXQgY8O0dMOpIGNsaWVudCAoY2zDqXMgcHVibGnDqWVzIHBhciBsZQptYW5pZmVzdGUsIGV4YWN0ZW1lbnQgY29tbWUgdW4gdmVyZGljdCkuIE1vZMOobGUgwqsgYmVhcmVyIMK7IHNhbnMgaWRlbnRpdMOpIDoKY29ow6lyZW50IGF2ZWMgbGEgY29uY2VwdGlvbiBwcml2YWN5LWZpcnN0IGRlIEJsb2tRUiAoYXVjdW4gY29tcHRlIHV0aWxpc2F0ZXVyKS4KIiIiCmZyb20gX19mdXR1cmVfXyBpbXBvcnQgYW5ub3RhdGlvbnMKCmltcG9ydCBqc29uCmZyb20gZGF0ZXRpbWUgaW1wb3J0IGRhdGV0aW1lLCB0aW1lZGVsdGEsIHRpbWV6b25lCmZyb20gdHlwaW5nIGltcG9ydCBPcHRpb25hbAoKZnJvbSBhcHAuc2VjdXJpdHkuc2lnbmluZyBpbXBvcnQgVmVyZGljdFNpZ25lciwgdmVyaWZ5X2VkMjU1MTksIHZlcmlmeV9tbGRzYQoKVFlQID0gImVudGl0bGVtZW50IgojIENoYW1wcyBzaWduw6lzIChvcmRyZSBpbmRpZmbDqXJlbnQgOiBsYSBjYW5vbmlzYXRpb24gdHJpZSBsZXMgY2zDqXMpLgpfUEFZTE9BRF9GSUVMRFMgPSAoImV4cCIsICJpYXQiLCAia2lkIiwgIm5vbmNlIiwgInBsYW4iLCAicHJvIiwgInR5cCIpCgoKZGVmIF9ub3coKSAtPiBkYXRldGltZToKICAgIHJldHVybiBkYXRldGltZS5ub3codGltZXpvbmUudXRjKQoKCmRlZiBfaXNvKGR0OiBkYXRldGltZSkgLT4gc3RyOgogICAgcmV0dXJuIGR0LnJlcGxhY2UobWljcm9zZWNvbmQ9MCkuaXNvZm9ybWF0KCkucmVwbGFjZSgiKzAwOjAwIiwgIloiKQoKCmRlZiBfcGFyc2VfaXNvKHM6IHN0cikgLT4gT3B0aW9uYWxbZGF0ZXRpbWVdOgogICAgdHJ5OgogICAgICAgIHJldHVybiBkYXRldGltZS5mcm9taXNvZm9ybWF0KHMucmVwbGFjZSgiWiIsICIrMDA6MDAiKSkKICAgIGV4Y2VwdCAoVmFsdWVFcnJvciwgQXR0cmlidXRlRXJyb3IpOgogICAgICAgIHJldHVybiBOb25lCgoKZGVmIF9jYW5vbmljYWwocGF5bG9hZDogZGljdCkgLT4gc3RyOgogICAgIiIiUmVwcsOpc2VudGF0aW9uIGNhbm9uaXF1ZSBkw6l0ZXJtaW5pc3RlIFNJR07DiUUgKGNsw6lzIHRyacOpZXMsIGNvbXBhY3QpLgoKICAgIExlIGNsaWVudCBET0lUIHJlcHJvZHVpcmUgRVhBQ1RFTUVOVCBjZSBmb3JtYXQgcG91ciB2w6lyaWZpZXIgbGEgc2lnbmF0dXJlIDoKICAgIEpTT04gVVRGLTgsIGNsw6lzIHRyacOpZXMsIHPDqXBhcmF0ZXVycyBjb21wYWN0cyAoIiwiLCI6IiksIGJvb2zDqWVuIEpTT04KICAgIHRydWUvZmFsc2UuIENoYW1wcyBpbmNsdXMgOiBleHAsIGlhdCwga2lkLCBub25jZSwgcGxhbiwgcHJvLCB0eXAuCiAgICAiIiIKICAgIG9iaiA9IHtrOiBwYXlsb2FkW2tdIGZvciBrIGluIF9QQVlMT0FEX0ZJRUxEU30KICAgIHJldHVybiBqc29uLmR1bXBzKG9iaiwgc29ydF9rZXlzPVRydWUsIHNlcGFyYXRvcnM9KCIsIiwgIjoiKSwKICAgICAgICAgICAgICAgICAgICAgIGVuc3VyZV9hc2NpaT1GYWxzZSkKCgpkZWYgc2lnbl9lbnRpdGxlbWVudChzaWduZXI6IFZlcmRpY3RTaWduZXIsICosIHBybzogYm9vbCwgcGxhbjogc3RyLAogICAgICAgICAgICAgICAgICAgICB0dGxfc2Vjb25kczogaW50LCBub25jZTogc3RyKSAtPiBzdHI6CiAgICAiIiLDiW1ldCB1biBqZXRvbiBkJ2VudGl0bGVtZW50IHNpZ27DqSAoSlNPTiBjb21wYWN0LCBwcsOqdCDDoCBtZXR0cmUgZW4gY2FjaGUpLiIiIgogICAgbm93ID0gX25vdygpCiAgICBwYXlsb2FkID0gewogICAgICAgICJ0eXAiOiBUWVAsCiAgICAgICAgInBybyI6IGJvb2wocHJvKSwKICAgICAgICAicGxhbiI6IHBsYW4sCiAgICAgICAgImlhdCI6IF9pc28obm93KSwKICAgICAgICAiZXhwIjogX2lzbyhub3cgKyB0aW1lZGVsdGEoc2Vjb25kcz1pbnQodHRsX3NlY29uZHMpKSksCiAgICAgICAgImtpZCI6IHNpZ25lci5rZXlfaWQsCiAgICAgICAgIm5vbmNlIjogbm9uY2UsCiAgICB9CiAgICBidW5kbGUgPSBzaWduZXIuc2lnbihfY2Fub25pY2FsKHBheWxvYWQpKQogICAgdG9rZW4gPSBkaWN0KHBheWxvYWQpCiAgICB0b2tlblsic2lnX2VkMjU1MTkiXSA9IGJ1bmRsZS5lZDI1NTE5X2I2NAogICAgdG9rZW5bInNpZ19tbGRzYTY1Il0gPSBidW5kbGUubWxkc2E2NV9iNjQKICAgIHJldHVybiBqc29uLmR1bXBzKHRva2VuLCBzZXBhcmF0b3JzPSgiLCIsICI6IiksIGVuc3VyZV9hc2NpaT1GYWxzZSkKCgpkZWYgdmVyaWZ5X2VudGl0bGVtZW50KHRva2VuOiBzdHIsIHNpZ25lcjogVmVyZGljdFNpZ25lcikgLT4gT3B0aW9uYWxbZGljdF06CiAgICAiIiJWw6lyaWZpZSB1biBqZXRvbiAoc2lnbmF0dXJlICsgZnJhw65jaGV1ciArIGNsw6kpLiBSZW52b2llIHtwcm8scGxhbixleHB9IG91IE5vbmUuCgogICAgUmVmdXNlIHNpIDogSlNPTiBpbnZhbGlkZSwgdHlwZSBpbmNvcnJlY3QsIGNoYW1wIG1hbnF1YW50LCBraWQgZGlmZsOpcmVudCBkZQogICAgbGEgY2zDqSBjb3VyYW50ZSwgc2lnbmF0dXJlIEVkMjU1MTkgKG91IE1MLURTQSBzaSBwcsOpc2VudGUpIGludmFsaWRlLCBvdQogICAgamV0b24gZXhwaXLDqS4gUmVudm9pZSBOb25lIGRhbnMgdG91cyBjZXMgY2FzIChmYWlsLWNsb3NlZCkuCiAgICAiIiIKICAgIGlmIG5vdCB0b2tlbjoKICAgICAgICByZXR1cm4gTm9uZQogICAgdHJ5OgogICAgICAgIGRhdGEgPSBqc29uLmxvYWRzKHRva2VuKQogICAgZXhjZXB0IChWYWx1ZUVycm9yLCBUeXBlRXJyb3IpOgogICAgICAgIHJldHVybiBOb25lCiAgICBpZiBub3QgaXNpbnN0YW5jZShkYXRhLCBkaWN0KSBvciBkYXRhLmdldCgidHlwIikgIT0gVFlQOgogICAgICAgIHJldHVybiBOb25lCiAgICBpZiBhbnkoZiBub3QgaW4gZGF0YSBmb3IgZiBpbiBfUEFZTE9BRF9GSUVMRFMpOgogICAgICAgIHJldHVybiBOb25lCiAgICBpZiBkYXRhLmdldCgia2lkIikgIT0gc2lnbmVyLmtleV9pZDoKICAgICAgICByZXR1cm4gTm9uZQogICAgY2Fub25pY2FsID0gX2Nhbm9uaWNhbChkYXRhKQogICAgaWYgbm90IHZlcmlmeV9lZDI1NTE5KGNhbm9uaWNhbCwgZGF0YS5nZXQoInNpZ19lZDI1NTE5IiwgIiIpLAogICAgICAgICAgICAgICAgICAgICAgICAgIHNpZ25lci5wdWJsaWNfa2V5X2VkMjU1MTlfYjY0KToKICAgICAgICByZXR1cm4gTm9uZQogICAgIyBNTC1EU0EgOiB2w6lyaWZpw6kgcydpbCBlc3QgcHLDqXNlbnQgZXQgcXVlIGxhIGNsw6kgUFEgZXhpc3RlLgogICAgaWYgc2lnbmVyLnBxX2VuYWJsZWQgYW5kIGRhdGEuZ2V0KCJzaWdfbWxkc2E2NSIpOgogICAgICAgIGlmIG5vdCB2ZXJpZnlfbWxkc2EoY2Fub25pY2FsLCBkYXRhWyJzaWdfbWxkc2E2NSJdLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgc2lnbmVyLnB1YmxpY19rZXlfbWxkc2E2NV9iNjQpOgogICAgICAgICAgICByZXR1cm4gTm9uZQogICAgZXhwID0gX3BhcnNlX2lzbyhkYXRhLmdldCgiZXhwIiwgIiIpKQogICAgaWYgZXhwIGlzIE5vbmUgb3IgZXhwIDw9IF9ub3coKToKICAgICAgICByZXR1cm4gTm9uZQogICAgcmV0dXJuIHsicHJvIjogYm9vbChkYXRhLmdldCgicHJvIikpLCAicGxhbiI6IGRhdGEuZ2V0KCJwbGFuIiksCiAgICAgICAgICAgICJleHAiOiBkYXRhLmdldCgiZXhwIil9Cg=='
SCH=('ICAgICMgSGFzaCBkZSBsYSBzb3VyY2Ugc2Nhbm7DqWUgKHBvdXIgbGEgY29ycsOpbGF0aW9uIGRlIGNvbnNlbnN1cyBjb21tdW5hdXRhaXJlKS4KICAgIHNvdXJjZV9oYXNoOiBPcHRpb25hbFtzdHJdID0gRmllbGQoCiAgICAgICAgZGVmYXVsdD1Ob25lLCBtYXhfbGVuZ3RoPTEyOCwKICAgICAgICBkZXNjcmlwdGlvbj0iSGFzaCBkZSBsYSBzb3VyY2UgKGNvcnLDqWxhdGlvbiBkZSBjb25zZW5zdXMgay1hbm9ueW1lKS4iLAogICAgKQ==', 'ICAgICMgSGFzaCBkZSBsYSBzb3VyY2Ugc2Nhbm7DqWUgKHBvdXIgbGEgY29ycsOpbGF0aW9uIGRlIGNvbnNlbnN1cyBjb21tdW5hdXRhaXJlKS4KICAgIHNvdXJjZV9oYXNoOiBPcHRpb25hbFtzdHJdID0gRmllbGQoCiAgICAgICAgZGVmYXVsdD1Ob25lLCBtYXhfbGVuZ3RoPTEyOCwKICAgICAgICBkZXNjcmlwdGlvbj0iSGFzaCBkZSBsYSBzb3VyY2UgKGNvcnLDqWxhdGlvbiBkZSBjb25zZW5zdXMgay1hbm9ueW1lKS4iLAogICAgKQogICAgIyBKZXRvbiBkJ2VudGl0bGVtZW50IFBybyBzaWduw6kgKHJlcXVpcyBwb3VyIC92MS9hbmFseXplL2RlZXApLiDDiW1pcyBwYXIKICAgICMgL3YxL2JpbGxpbmcvdmVyaWZ5LCBtaXMgZW4gY2FjaGUgcGFyIGxlIGNsaWVudCBldCBwcsOpc2VudMOpIHRlbCBxdWVsLgogICAgZW50aXRsZW1lbnQ6IE9wdGlvbmFsW3N0cl0gPSBGaWVsZCgKICAgICAgICBkZWZhdWx0PU5vbmUsIG1heF9sZW5ndGg9MTIwMDAsCiAgICAgICAgZGVzY3JpcHRpb249IkpldG9uIGQnZW50aXRsZW1lbnQgUHJvIHNpZ27DqSAocGFsaWVyIHByb2ZvbmQgLyBQcm8pLiIsCiAgICAp', 'entitlement: Optional[str] = Field(')
RT=[('ZnJvbSBmYXN0YXBpIGltcG9ydCBBUElSb3V0ZXIsIERlcGVuZHMsIFJlcXVlc3QKCmZyb20gYXBwLmNvbmZpZyBpbXBvcnQgU2V0dGluZ3MsIGdldF9zZXR0aW5ncwpmcm9tIGFwcC5waXBlbGluZSBpbXBvcnQgYW5hbHl6ZSwgYnVpbGRfdGltZW91dF92ZXJkaWN0CmZyb20gYXBwLmFuYWx5emVycy5yZXB1dGF0aW9uX2thbm9uIGltcG9ydCBnZXRfc3RvcmU=', 'ZnJvbSBmYXN0YXBpIGltcG9ydCBBUElSb3V0ZXIsIERlcGVuZHMsIFJlcXVlc3QsIEhUVFBFeGNlcHRpb24KCmZyb20gYXBwLmNvbmZpZyBpbXBvcnQgU2V0dGluZ3MsIGdldF9zZXR0aW5ncwpmcm9tIGFwcC5waXBlbGluZSBpbXBvcnQgYW5hbHl6ZSwgYnVpbGRfdGltZW91dF92ZXJkaWN0CmZyb20gYXBwLmFuYWx5emVycy5yZXB1dGF0aW9uX2thbm9uIGltcG9ydCBnZXRfc3RvcmUKZnJvbSBhcHAuc2VjdXJpdHkuZW50aXRsZW1lbnQgaW1wb3J0IHZlcmlmeV9lbnRpdGxlbWVudA==', 'from app.security.entitlement import verify_entitlement'), ('ICAgIHRyeToKICAgICAgICByZXR1cm4gYXdhaXQgYXN5bmNpby53YWl0X2ZvcigKICAgICAgICAgICAgYW5hbHl6ZShwYXlsb2FkLCBzZXR0aW5ncywgc2lnbmVyKSwKICAgICAgICAgICAgdGltZW91dD1zZXR0aW5ncy5vdmVyYWxsX2J1ZGdldF9zZWNvbmRzLAogICAgICAgICkKICAgIGV4Y2VwdCBhc3luY2lvLlRpbWVvdXRFcnJvcjoKICAgICAgICByZXR1cm4gYnVpbGRfdGltZW91dF92ZXJkaWN0KHBheWxvYWQsIHNldHRpbmdzLCBzaWduZXIp', 'ICAgIHRyeToKICAgICAgICByZXR1cm4gYXdhaXQgYXN5bmNpby53YWl0X2ZvcigKICAgICAgICAgICAgYW5hbHl6ZShwYXlsb2FkLCBzZXR0aW5ncywgc2lnbmVyKSwKICAgICAgICAgICAgdGltZW91dD1zZXR0aW5ncy5vdmVyYWxsX2J1ZGdldF9zZWNvbmRzLAogICAgICAgICkKICAgIGV4Y2VwdCBhc3luY2lvLlRpbWVvdXRFcnJvcjoKICAgICAgICByZXR1cm4gYnVpbGRfdGltZW91dF92ZXJkaWN0KHBheWxvYWQsIHNldHRpbmdzLCBzaWduZXIpCgoKQHJvdXRlci5wb3N0KCIvdjEvYW5hbHl6ZS9kZWVwIiwgcmVzcG9uc2VfbW9kZWw9U2lnbmVkVmVyZGljdCwgdGFncz1bImFuYWx5c2lzIl0pCmFzeW5jIGRlZiBhbmFseXplX2RlZXBfcm91dGUoCiAgICBwYXlsb2FkOiBBbmFseXplUmVxdWVzdCwKICAgIHNldHRpbmdzOiBTZXR0aW5ncyA9IERlcGVuZHMoZ2V0X3NldHRpbmdzKSwKICAgIHNpZ25lcjogVmVyZGljdFNpZ25lciA9IERlcGVuZHMoZ2V0X3NpZ25lciksCikgLT4gU2lnbmVkVmVyZGljdDoKICAgICIiIkFuYWx5c2UgUFJPRk9OREUgKFBybykgOiBham91dGUgbGUgcmVuZHUgZHluYW1pcXVlIENocm9taXVtLgoKICAgIFLDqXNlcnbDqWUgYXV4IHBvcnRldXJzIGQndW4gZW50aXRsZW1lbnQgUHJvIHZhbGlkZS4gTGUgY2xpZW50IGwnYXBwZWxsZSBkZQogICAgZmHDp29uIEFTWU5DSFJPTkUsIEFQUsOIUyBhdm9pciBhZmZpY2jDqSBsZSB2ZXJkaWN0IHJhcGlkZSBkZSAvdjEvYW5hbHl6ZSwgcHVpcwogICAgbWV0IMOgIGpvdXIgbCdhZmZpY2hhZ2UgYXZlYyBjZSB2ZXJkaWN0IGFwcHJvZm9uZGkuIEVuIGwnYWJzZW5jZSBkJ2VudGl0bGVtZW50CiAgICB2YWxpZGUgOiA0MDIgKGxlIGNsaWVudCBhZmZpY2hlIGxlIHBheXdhbGwsIHNhbnMgYmxvcXVlciBsZSB2ZXJkaWN0IHJhcGlkZSkuCiAgICAiIiIKICAgIGVudCA9IHZlcmlmeV9lbnRpdGxlbWVudChwYXlsb2FkLmVudGl0bGVtZW50IG9yICIiLCBzaWduZXIpCiAgICBpZiBub3QgKGVudCBhbmQgZW50LmdldCgicHJvIikpOgogICAgICAgIHJhaXNlIEhUVFBFeGNlcHRpb24oc3RhdHVzX2NvZGU9NDAyLCBkZXRhaWw9InByb19yZXF1aXJlZCIpCiAgICB0cnk6CiAgICAgICAgcmV0dXJuIGF3YWl0IGFzeW5jaW8ud2FpdF9mb3IoCiAgICAgICAgICAgIGFuYWx5emUocGF5bG9hZCwgc2V0dGluZ3MsIHNpZ25lciwgZGVlcD1UcnVlKSwKICAgICAgICAgICAgdGltZW91dD1zZXR0aW5ncy5vdmVyYWxsX2J1ZGdldF9zZWNvbmRzLAogICAgICAgICkKICAgIGV4Y2VwdCBhc3luY2lvLlRpbWVvdXRFcnJvcjoKICAgICAgICByZXR1cm4gYnVpbGRfdGltZW91dF92ZXJkaWN0KHBheWxvYWQsIHNldHRpbmdzLCBzaWduZXIp', '/v1/analyze/deep')]

def write_new(path, content_b64, marker):
    if os.path.exists(path):
        cur=io.open(path,"r",encoding="utf-8").read()
        if marker in cur:
            print("  [OK   ] %s : deja present (idempotent)"%path); return True
        print("  [ABORT] %s : existe deja SANS le marqueur -> NON ecrase"%path); return False
    content=dec(content_b64)
    try: ast.parse(content)
    except SyntaxError as e:
        print("  [ABORT] %s : contenu invalide (%s)"%(path,e)); return False
    os.makedirs(os.path.dirname(path), exist_ok=True)
    io.open(path,"w",encoding="utf-8").write(content)
    print("  [CREATE] %s : cree"%path); return True

def apply_edits(path, edits):
    if not os.path.exists(path):
        print("  [ABORT] %s introuvable"%path); return False
    src=io.open(path,"r",encoding="utf-8").read(); changed=False
    for old_b,new_b,marker in edits:
        if marker in src: continue
        old=dec(old_b)
        if old not in src:
            print("  [ABORT] %s : ancre absente (%s) -> NON ecrit"%(path,marker)); return False
        src=src.replace(old,dec(new_b),1); changed=True
    if not changed:
        print("  [OK   ] %s : deja applique (idempotent)"%path); return True
    try: ast.parse(src)
    except SyntaxError as e:
        print("  [ABORT] %s : syntaxe invalide -> NON ecrit (%s)"%(path,e)); return False
    io.open(path,"w",encoding="utf-8").write(src)
    print("  [PATCH] %s : modifie"%path); return True

def main():
    ok=True
    ok&=write_new("app/security/entitlement.py", ENT_B64, "def verify_entitlement")
    ok&=apply_edits("app/schemas.py", [SCH])
    ok&=apply_edits("app/api/routes.py", RT)
    if not ok: sys.exit(1)
    print("\n>>> Termine. Reconstruisez l'image puis redemarrez le conteneur.")

if __name__=="__main__":
    main()
