#!/usr/bin/env python3
# -*- coding: ascii -*-
"""
Patch de reconciliation M1 (BlokQR) : retablit le decoupage des paliers dans
app/pipeline.py.
  (a) ajoute le parametre 'deep: bool = False' a analyze() ;
  (b) separe la cle de cache par palier (fast/deep) sans toucher cache_key() ;
  (c) remplace le bloc unique par deux branches :
        - else (GRATUIT/RAPIDE) : threat intel + age du domaine, SANS rendu ;
        - if deep (PRO)         : rendu Chromium + threat intel + age du domaine.
Les routes sont deja correctes (/v1/analyze -> deep defaut False ;
/v1/analyze/deep -> deep=True). Idempotent, abort si ancre absente, AST validee.
Lancer depuis /opt/blokqr/backend.
"""
import ast, base64, os, sys

def d(s): return base64.b64decode(s).decode("utf-8")

PATH = "app/pipeline.py"
EDITS = [
    ("YXN5bmMgZGVmIGFuYWx5emUoCiAgICByZXF1ZXN0OiBBbmFseXplUmVxdWVzdCwgc2V0dGluZ3M6IFNldHRpbmdzLCBzaWduZXI6IFZlcmRpY3RTaWduZXIKKSAtPiBTaWduZWRWZXJkaWN0OgogICAgIiIiRXjDqWN1dGUgbGUgcGlwZWxpbmUgY29tcGxldCBldCByZW52b2llIHVuIHZlcmRpY3Qgc2lnbsOpLiIiIgo=", "YXN5bmMgZGVmIGFuYWx5emUoCiAgICByZXF1ZXN0OiBBbmFseXplUmVxdWVzdCwgc2V0dGluZ3M6IFNldHRpbmdzLCBzaWduZXI6IFZlcmRpY3RTaWduZXIsCiAgICAqLCBkZWVwOiBib29sID0gRmFsc2UsCikgLT4gU2lnbmVkVmVyZGljdDoKICAgICIiIkV4w6ljdXRlIGxlIHBpcGVsaW5lIGV0IHJlbnZvaWUgdW4gdmVyZGljdCBzaWduw6kuCgogICAgZGVlcD1GYWxzZSAoZ3JhdHVpdCkgOiBwYWxpZXIgUkFQSURFIHNhbnMgcmVuZHUgQ2hyb21pdW0gKGxleGljYWwgKwogICAgcmVkaXJlY3Rpb25zICsgZG9tYWluZSArIHRocmVhdCBpbnRlbCArIMOiZ2UpIC0+IHLDqXBvbnNlIHJhcGlkZSBldCBmaWFibGUuCiAgICBkZWVwPVRydWUgKFBybywgdmlhIC92MS9hbmFseXplL2RlZXApIDogYWpvdXRlIGxlIHJlbmR1IGR5bmFtaXF1ZSBDaHJvbWl1bS4KICAgICIiIgo="),
    ("ICAgIGNhY2hlID0gZ2V0X2NhY2hlKHNldHRpbmdzKQogICAgY2tleSA9IGNhY2hlX2tleShyZXF1ZXN0KQo=", "ICAgIGNhY2hlID0gZ2V0X2NhY2hlKHNldHRpbmdzKQogICAgY2tleSA9ICgiZGVlcDoiIGlmIGRlZXAgZWxzZSAiZmFzdDoiKSArIHN0cihjYWNoZV9rZXkocmVxdWVzdCkpCg=="),
    ("ICAgICAgICAjIDUrNi4gQW5hbHlzZSBkeW5hbWlxdWUgKyB0aHJlYXQgaW50ZWwgRU4gUEFSQUxMRUxFLCBkeW5hbWlxdWUgQk9STkVFLgogICAgICAgIGlmIG5vdCBwcml2YWN5X2hvbGQ6CiAgICAgICAgICAgIGludGVsX3RhcmdldCA9IHJlcG9ydC5maW5hbF90YXJnZXQgb3IgY2xhc3NpZmllZC51cmwKCiAgICAgICAgICAgIGFzeW5jIGRlZiBfcnVuX2R5bmFtaWMoKToKICAgICAgICAgICAgICAgIGlmIG5vdCBmaW5hbF91cmw6CiAgICAgICAgICAgICAgICAgICAgcmV0dXJuIE5vbmUKICAgICAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgICAgICByZXR1cm4gYXdhaXQgYXN5bmNpby53YWl0X2ZvcigKICAgICAgICAgICAgICAgICAgICAgICAgYW5hbHl6ZV9keW5hbWljKAogICAgICAgICAgICAgICAgICAgICAgICAgICAgZmluYWxfdXJsLCBzZXR0aW5ncywKICAgICAgICAgICAgICAgICAgICAgICAgICAgIHdhbnRfc2NyZWVuc2hvdD1yZXF1ZXN0LndhbnRfc2NyZWVuc2hvdCwKICAgICAgICAgICAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgICAgICAgICAgICAgdGltZW91dD1zZXR0aW5ncy5keW5hbWljX2J1ZGdldF9zZWNvbmRzLAogICAgICAgICAgICAgICAgICAgICkKICAgICAgICAgICAgICAgIGV4Y2VwdCBhc3luY2lvLlRpbWVvdXRFcnJvcjoKICAgICAgICAgICAgICAgICAgICByZXR1cm4gTm9uZQoKICAgICAgICAgICAgZHluLCBpbnRlbCwgYWdlX3NpZyA9IGF3YWl0IGFzeW5jaW8uZ2F0aGVyKAogICAgICAgICAgICAgICAgX3J1bl9keW5hbWljKCksCiAgICAgICAgICAgICAgICBnYXRoZXJfdGhyZWF0X2ludGVsKGludGVsX3RhcmdldCwgc2V0dGluZ3MpLAogICAgICAgICAgICAgICAgZG9tYWluX2FnZV9zaWduYWwocmVwb3J0LmRvbWFpbl9yZWdpc3RyYWJsZSwgc2V0dGluZ3MpLAogICAgICAgICAgICApCiAgICAgICAgICAgIHJlcG9ydC50aHJlYXRfaW50ZWwgPSBpbnRlbAogICAgICAgICAgICBpZiBhZ2Vfc2lnOgogICAgICAgICAgICAgICAgc2lnbmFscy5hcHBlbmQoYWdlX3NpZykKCiAgICAgICAgICAgIGlmIGR5biBpcyBub3QgTm9uZSBhbmQgZHluLmF2YWlsYWJsZToKICAgICAgICAgICAgICAgIHJlcG9ydC5jbG9ha2luZ19kZXRlY3RlZCA9IGR5bi5jbG9ha2luZ19kZXRlY3RlZAogICAgICAgICAgICAgICAgcmVwb3J0LmdhdGluZ19kZXRlY3RlZCA9IGR5bi5nYXRpbmdfZGV0ZWN0ZWQKICAgICAgICAgICAgICAgIGlmIGR5bi5pbXBlcnNvbmF0ZWRfYnJhbmQ6CiAgICAgICAgICAgICAgICAgICAgcmVwb3J0LmxvZ2luX3BhZ2VfaW1wZXJzb25hdGlvbiA9IGR5bi5pbXBlcnNvbmF0ZWRfYnJhbmQKICAgICAgICAgICAgICAgIHJlcG9ydC5zY3JlZW5zaG90X2I2NCA9IGR5bi5zY3JlZW5zaG90X2I2NAogICAgICAgICAgICAgICAgc2lnbmFscy5leHRlbmQoZHluLnNpZ25hbHMpCiAgICAgICAgICAgICAgICBpZiBkeW4uZmluYWxfdXJsIGFuZCBkeW4uZmluYWxfdXJsICE9IGZpbmFsX3VybDoKICAgICAgICAgICAgICAgICAgICByZXBvcnQuZmluYWxfdGFyZ2V0ID0gZHluLmZpbmFsX3VybAogICAgICAgICAgICAgICAgICAgIHJlcG9ydC5kaXNwbGF5ZWRfdmFsdWUgPSBkeW4uZmluYWxfdXJsCiAgICAgICAgICAgIGVsaWYgZmluYWxfdXJsOgogICAgICAgICAgICAgICAgc2lnbmFscy5hcHBlbmQoU2lnbmFsKAogICAgICAgICAgICAgICAgICAgIGNvZGU9ImR5bmFtaWNfZXJyb3IiLCB0aXRsZT0iQW5hbHlzZSBkeW5hbWlxdWUgaW5jb21wbGV0ZSIsCiAgICAgICAgICAgICAgICAgICAgZGV0YWlsPSJCdWRnZXQgZGUgdGVtcHMgZHUgcmVuZHUgZHluYW1pcXVlIGRlcGFzc2UuIiwKICAgICAgICAgICAgICAgICAgICBzZXZlcml0eT1TZXZlcml0eS5JTkZPLCB3ZWlnaHQ9MCwgc291cmNlPSJkeW5hbWljIikpCg==", "ICAgICAgICAjIDUrNi4gVGhyZWF0IGludGVsICsgw6JnZSBkdSBkb21haW5lICh0b3Vqb3VycykgOyByZW5kdSBDaHJvbWl1bSBlbiBQUk8uCiAgICAgICAgIyAgICAgIFBhbGllciBSQVBJREUgKGdyYXR1aXQpIDogcGFzIGRlIHJlbmR1IHN5bmNocm9uZSAtPiBmaW4gZGUgbGEKICAgICAgICAjICAgICAgdmFyaWFuY2UgZGUgbGF0ZW5jZSAowqsgZmFpbGVkIC0+IFNhZmUgwrspLiBQYWxpZXIgUFJPRk9ORCAoUHJvKSA6CiAgICAgICAgIyAgICAgIGFqb3V0ZSBsZSByZW5kdSBkeW5hbWlxdWUgYm9ybsOpIHBhciB1biBidWRnZXQgZGUgdGVtcHMuCiAgICAgICAgaWYgbm90IHByaXZhY3lfaG9sZDoKICAgICAgICAgICAgaW50ZWxfdGFyZ2V0ID0gcmVwb3J0LmZpbmFsX3RhcmdldCBvciBjbGFzc2lmaWVkLnVybAoKICAgICAgICAgICAgaWYgZGVlcDoKICAgICAgICAgICAgICAgIGFzeW5jIGRlZiBfcnVuX2R5bmFtaWMoKToKICAgICAgICAgICAgICAgICAgICBpZiBub3QgZmluYWxfdXJsOgogICAgICAgICAgICAgICAgICAgICAgICByZXR1cm4gTm9uZQogICAgICAgICAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgICAgICAgICAgcmV0dXJuIGF3YWl0IGFzeW5jaW8ud2FpdF9mb3IoCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBhbmFseXplX2R5bmFtaWMoCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZmluYWxfdXJsLCBzZXR0aW5ncywKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB3YW50X3NjcmVlbnNob3Q9cmVxdWVzdC53YW50X3NjcmVlbnNob3QsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgdGltZW91dD1zZXR0aW5ncy5keW5hbWljX2J1ZGdldF9zZWNvbmRzLAogICAgICAgICAgICAgICAgICAgICAgICApCiAgICAgICAgICAgICAgICAgICAgZXhjZXB0IGFzeW5jaW8uVGltZW91dEVycm9yOgogICAgICAgICAgICAgICAgICAgICAgICByZXR1cm4gTm9uZQoKICAgICAgICAgICAgICAgIGR5biwgaW50ZWwsIGFnZV9zaWcgPSBhd2FpdCBhc3luY2lvLmdhdGhlcigKICAgICAgICAgICAgICAgICAgICBfcnVuX2R5bmFtaWMoKSwKICAgICAgICAgICAgICAgICAgICBnYXRoZXJfdGhyZWF0X2ludGVsKGludGVsX3RhcmdldCwgc2V0dGluZ3MpLAogICAgICAgICAgICAgICAgICAgIGRvbWFpbl9hZ2Vfc2lnbmFsKHJlcG9ydC5kb21haW5fcmVnaXN0cmFibGUsIHNldHRpbmdzKSwKICAgICAgICAgICAgICAgICkKICAgICAgICAgICAgICAgIHJlcG9ydC50aHJlYXRfaW50ZWwgPSBpbnRlbAogICAgICAgICAgICAgICAgaWYgYWdlX3NpZzoKICAgICAgICAgICAgICAgICAgICBzaWduYWxzLmFwcGVuZChhZ2Vfc2lnKQoKICAgICAgICAgICAgICAgIGlmIGR5biBpcyBub3QgTm9uZSBhbmQgZHluLmF2YWlsYWJsZToKICAgICAgICAgICAgICAgICAgICByZXBvcnQuY2xvYWtpbmdfZGV0ZWN0ZWQgPSBkeW4uY2xvYWtpbmdfZGV0ZWN0ZWQKICAgICAgICAgICAgICAgICAgICByZXBvcnQuZ2F0aW5nX2RldGVjdGVkID0gZHluLmdhdGluZ19kZXRlY3RlZAogICAgICAgICAgICAgICAgICAgIGlmIGR5bi5pbXBlcnNvbmF0ZWRfYnJhbmQ6CiAgICAgICAgICAgICAgICAgICAgICAgIHJlcG9ydC5sb2dpbl9wYWdlX2ltcGVyc29uYXRpb24gPSBkeW4uaW1wZXJzb25hdGVkX2JyYW5kCiAgICAgICAgICAgICAgICAgICAgcmVwb3J0LnNjcmVlbnNob3RfYjY0ID0gZHluLnNjcmVlbnNob3RfYjY0CiAgICAgICAgICAgICAgICAgICAgc2lnbmFscy5leHRlbmQoZHluLnNpZ25hbHMpCiAgICAgICAgICAgICAgICAgICAgaWYgZHluLmZpbmFsX3VybCBhbmQgZHluLmZpbmFsX3VybCAhPSBmaW5hbF91cmw6CiAgICAgICAgICAgICAgICAgICAgICAgIHJlcG9ydC5maW5hbF90YXJnZXQgPSBkeW4uZmluYWxfdXJsCiAgICAgICAgICAgICAgICAgICAgICAgIHJlcG9ydC5kaXNwbGF5ZWRfdmFsdWUgPSBkeW4uZmluYWxfdXJsCiAgICAgICAgICAgICAgICBlbGlmIGZpbmFsX3VybDoKICAgICAgICAgICAgICAgICAgICBzaWduYWxzLmFwcGVuZChTaWduYWwoCiAgICAgICAgICAgICAgICAgICAgICAgIGNvZGU9ImR5bmFtaWNfZXJyb3IiLCB0aXRsZT0iQW5hbHlzZSBkeW5hbWlxdWUgaW5jb21wbGV0ZSIsCiAgICAgICAgICAgICAgICAgICAgICAgIGRldGFpbD0iQnVkZ2V0IGRlIHRlbXBzIGR1IHJlbmR1IGR5bmFtaXF1ZSBkZXBhc3NlLiIsCiAgICAgICAgICAgICAgICAgICAgICAgIHNldmVyaXR5PVNldmVyaXR5LklORk8sIHdlaWdodD0wLCBzb3VyY2U9ImR5bmFtaWMiKSkKICAgICAgICAgICAgZWxzZToKICAgICAgICAgICAgICAgIGludGVsLCBhZ2Vfc2lnID0gYXdhaXQgYXN5bmNpby5nYXRoZXIoCiAgICAgICAgICAgICAgICAgICAgZ2F0aGVyX3RocmVhdF9pbnRlbChpbnRlbF90YXJnZXQsIHNldHRpbmdzKSwKICAgICAgICAgICAgICAgICAgICBkb21haW5fYWdlX3NpZ25hbChyZXBvcnQuZG9tYWluX3JlZ2lzdHJhYmxlLCBzZXR0aW5ncyksCiAgICAgICAgICAgICAgICApCiAgICAgICAgICAgICAgICByZXBvcnQudGhyZWF0X2ludGVsID0gaW50ZWwKICAgICAgICAgICAgICAgIGlmIGFnZV9zaWc6CiAgICAgICAgICAgICAgICAgICAgc2lnbmFscy5hcHBlbmQoYWdlX3NpZykK"),
]

def main():
    if not os.path.exists(PATH):
        print("[ABORT] %s introuvable" % PATH); sys.exit(1)
    src = open(PATH, encoding="utf-8").read()

    if "from app.analyzers.domain_age import domain_age_signal" not in src:
        print("[ABORT] import domain_age_signal absent : appliquez d'abord patch_domain_age.py")
        sys.exit(1)

    applied = 0
    for i, (old_b, new_b) in enumerate(EDITS, 1):
        old, new = d(old_b), d(new_b)
        if new in src:
            print("[SKIP] edition %d : deja appliquee" % i); continue
        if old not in src:
            print("[ABORT] edition %d : ancre introuvable -> AUCUNE ecriture" % i)
            sys.exit(1)
        src = src.replace(old, new, 1)
        applied += 1
        print("[OK]   edition %d appliquee" % i)

    if applied:
        ast.parse(src)  # validation globale avant ecriture
        with open(PATH, "w", encoding="utf-8") as f:
            f.write(src)
        print("\n[OK] %s reconcilie (%d edition(s)). Reconstruisez le conteneur." % (PATH, applied))
    else:
        print("\nRien a faire (deja reconcilie).")

if __name__ == "__main__":
    main()
